### ISSUE TITLE
Pictures with no preview

### ISSUE THREAD

**Issue by AugustoEst** [krazykira/CuXtomCam#2]
Is it possible to use CuXtomCam to take pictures with no preview on the Glass?

**Comment by krazykira** [comment]
Yes its possible. That is how it behaves by default. Once it takes a picture it returns to the calling activities `onActivityResult()` method. Check out the [Readme.md](https://github.com/krazykira/CuXtomCam) or [sample app](https://github.com/krazykira/CuXtomCam-Sample-App) to find out on how to use it.
